/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

import Hospital.Patient.Patient;
import Hospital.Doctor.Doctor;
import Package.ConnectionProvider;
import User.CreateUser;
import com.mysql.cj.jdbc.result.ResultSetMetaData;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;

/**
 *
 * @author Yamini Manral
 */
public class HospitalAdmin extends javax.swing.JFrame {

    String hospitalid;

    /**
     * Creates new form HospitalAdmin
     */
    public HospitalAdmin(String hid) {

        hospitalid = hid;
        initComponents();
    }

    public HospitalAdmin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jTextField9 = new javax.swing.JTextField();
        jLabel34 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jButton16 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel29 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        lblPassword4 = new javax.swing.JLabel();
        cbRole6 = new javax.swing.JComboBox<>();
        lblRole4 = new javax.swing.JLabel();
        pfPassword4 = new javax.swing.JPasswordField();
        txtUsername4 = new javax.swing.JTextField();
        lblUserName4 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel41 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        txtPname1 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        btncreate1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton11 = new javax.swing.JButton();
        jButton18 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtUsername = new javax.swing.JTextField();
        btnCreateUser = new javax.swing.JButton();
        lblUserName = new javax.swing.JLabel();
        cbRole = new javax.swing.JComboBox<>();
        lblRole = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jTabbedPane1.setBackground(new java.awt.Color(244, 219, 216));
        jTabbedPane1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jPanel2.setBackground(new java.awt.Color(192, 152, 145));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextField9.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextField9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField9ActionPerformed(evt);
            }
        });
        jPanel2.add(jTextField9, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 350, 206, 30));

        jLabel34.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel34.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel34.setText("Delete Doctor");
        jPanel2.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 300, 378, -1));

        jLabel16.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel16.setText("Name");
        jPanel2.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 350, 69, -1));

        jButton5.setBackground(new java.awt.Color(255, 102, 102));
        jButton5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton5.setText("Delete Doctor");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 390, 147, 55));

        jTable2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Doctor ID", "Name", "Hospital"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        jPanel2.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 80, 400, 140));

        jButton16.setBackground(new java.awt.Color(0, 0, 0));
        jButton16.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton16.setForeground(new java.awt.Color(255, 255, 255));
        jButton16.setText("View Details");
        jButton16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton16ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton16, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 230, -1, 44));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("HospitalID");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 290, 90, 30));

        jButton1.setBackground(new java.awt.Color(0, 0, 0));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Create new Doctor");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 340, 172, 55));

        jLabel29.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel29.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel29.setText("Hospital ID");
        jPanel2.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, 110, 30));

        jLabel33.setFont(new java.awt.Font("Segoe UI Historic", 1, 24)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(42, 8, 0));
        jLabel33.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel33.setText("Doctor Creation");
        jPanel2.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(-20, 60, 430, 53));

        lblPassword4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblPassword4.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblPassword4.setText("Password");
        jPanel2.add(lblPassword4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, 86, -1));

        cbRole6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cbRole6.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Doctor" }));
        jPanel2.add(cbRole6, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 120, 170, 33));

        lblRole4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblRole4.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblRole4.setText("Role");
        jPanel2.add(lblRole4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, 86, -1));

        pfPassword4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pfPassword4ActionPerformed(evt);
            }
        });
        jPanel2.add(pfPassword4, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 200, 170, 36));
        jPanel2.add(txtUsername4, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 160, 170, 33));

        lblUserName4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblUserName4.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblUserName4.setText("Username");
        jPanel2.add(lblUserName4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, 86, -1));

        jTextField3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jPanel2.add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 250, 170, -1));

        jLabel41.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel41.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel41.setText("Name");
        jPanel2.add(jLabel41, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 250, 69, 30));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setText("Hospital Administrator");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 20, -1, -1));

        jTabbedPane1.addTab("Doctors", jPanel2);

        jPanel3.setBackground(new java.awt.Color(192, 152, 145));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Delete Patient");
        jPanel3.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 320, 330, -1));

        txtPname1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPname1ActionPerformed(evt);
            }
        });
        jPanel3.add(txtPname1, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 360, 140, 30));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel12.setText("Patient ID");
        jPanel3.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 360, 106, 30));

        btncreate1.setBackground(new java.awt.Color(255, 102, 102));
        btncreate1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btncreate1.setText("Delete Patient");
        btncreate1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncreate1ActionPerformed(evt);
            }
        });
        jPanel3.add(btncreate1, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 410, 145, 44));

        jTable1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Patient ID", "Name"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jPanel3.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 90, 400, 140));

        jButton11.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton11.setText("View Details");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton11, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 240, -1, 44));

        jButton18.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton18.setText("Logout");
        jButton18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton18ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton18, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 40, 103, 30));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setText("Hospital Administrator");
        jPanel3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 10, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI Historic", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(42, 8, 0));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Patient Update");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 340, 53));
        jPanel3.add(txtUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 230, 170, 33));

        btnCreateUser.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnCreateUser.setText("Update");
        btnCreateUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateUserActionPerformed(evt);
            }
        });
        jPanel3.add(btnCreateUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 320, 119, 45));

        lblUserName.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblUserName.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblUserName.setText("Username");
        jPanel3.add(lblUserName, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, 86, 30));

        cbRole.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cbRole.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Patient" }));
        jPanel3.add(cbRole, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 180, 170, 33));

        lblRole.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblRole.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblRole.setText("Role");
        jPanel3.add(lblRole, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, 86, 30));

        jLabel30.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel30.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel30.setText("Hospital ID");
        jPanel3.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, 110, 30));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("HospitalID");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 270, 90, 30));

        jTabbedPane1.addTab("Patients", jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 801, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 546, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtPname1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPname1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPname1ActionPerformed

    private void jTextField9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField9ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:

        //delete doctor
        Doctor.DeleteDoctor(jTextField9.getText());
        jTextField9.setText("");

    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        // TODO add your handling code here:

        //BUTTON TO VIEW PATIENT DETAILS/press only once
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();

        String name, id;
        model.setRowCount(0);
        try {
            Connection connection = ConnectionProvider.Connect();
            Statement statement = connection.createStatement();
            String query = "select persondirectory.personid,  persondirectory.name from hospital.persondirectory WHERE role = 'Patient' "
                    + "AND hospitalid = '" + hospitalid +"'";
            ResultSet rs = statement.executeQuery(query);

            //push column values to the table fields
            ResultSetMetaData rsmd = (ResultSetMetaData) rs.getMetaData();
            while (rs.next()) {
                id = rs.getString(1);
                name = rs.getString(2);
                String[] row = {id, name};
                model.addRow(row);
            }
            connection.close();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }

    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton16ActionPerformed
        // TODO add your handling code here:

        //BUTTON TO VIEW DOCTOR DETAILS FROM THE DATABASE
        DefaultTableModel model = (DefaultTableModel) jTable2.getModel();
        String id;
        String name;
        String hospital;
        model.setRowCount(0);
        try {
            Connection connection = ConnectionProvider.Connect();
            Statement statement = connection.createStatement();

            ResultSet rs = statement.executeQuery("select persondirectory.personid, persondirectory.name, hospitaldirectory.name from "
                    + "hospital.persondirectory, hospital.hospitaldirectory "
                    +"WHERE persondirectory.hospitalid = hospitaldirectory.hospitalid AND persondirectory.role = 'Doctor' AND hospitaldirectory.hospitalid ='" + hospitalid + "'");

            //push column values to the table fields
            ResultSetMetaData rsmd = (ResultSetMetaData) rs.getMetaData();
            while (rs.next()) {
                id = rs.getString(1);
                name = rs.getString(2);
                hospital = rs.getString(3);
//                community = rs.getString(4);
                String[] row = {id, name, hospital};
                model.addRow(row);
            }
            connection.close();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_jButton16ActionPerformed

    //hospital admin --> patient tab --> delete patient //require hospital id
    private void btncreate1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncreate1ActionPerformed
        // TODO add your handling code here:
        
        //delete patient
        
        String id = txtPname1.getText();
        
        try {
            Connection connection = ConnectionProvider.Connect();
            Statement statement = connection.createStatement();
           
            
            if (id.equals("")) {
                JOptionPane.showMessageDialog(null, "Please enter a Patient ID to proceed!");
            } else {
                String query2 = "delete from hospital.persondirectory where personid = '" + id + "' AND role = 'Patient' AND hospitalid ='" + hospitalid + "'  ";
            
                statement.executeUpdate(query2);
                JOptionPane.showMessageDialog(null, "Patient deleted!");
            }
            connection.close();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
        txtPname1.setText("");
    }//GEN-LAST:event_btncreate1ActionPerformed

    private void pfPassword4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pfPassword4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pfPassword4ActionPerformed

    private void jButton18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton18ActionPerformed
        // TODO add your handling code here:
        //SYSTEM ADMIN LOGOUT BUTTON FUNCTIONALITY

        int a = JOptionPane.showConfirmDialog(null, "Do you really wanna logout?", "Select", JOptionPane.YES_NO_OPTION);
        if (a == 0) {
            dispose();
            new Login().setVisible(true);
        }
    }//GEN-LAST:event_jButton18ActionPerformed

    private void btnCreateUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateUserActionPerformed
        // TODO add your handling code here:

        //patient update button action
        String username = txtUsername.getText();

        Patient.UpdatePatient(username, hospitalid);

    }//GEN-LAST:event_btnCreateUserActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:

        //add new doctor to the doctor table
        String name = jTextField3.getText();
        String role= cbRole6.getSelectedItem().toString();
        String username = txtUsername4.getText();
        String password = pfPassword4.getText();
        String cid = null;

        CreateUser.NewUser(role, username, password, name, cid, hospitalid);

        jTextField3.setText("");
        txtUsername4.setText("");
        pfPassword4.setText("");
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("FlatLaf Light".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HospitalAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HospitalAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HospitalAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HospitalAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HospitalAdmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCreateUser;
    private javax.swing.JButton btncreate1;
    private javax.swing.JComboBox<String> cbRole;
    private javax.swing.JComboBox<String> cbRole6;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField9;
    private javax.swing.JLabel lblPassword4;
    private javax.swing.JLabel lblRole;
    private javax.swing.JLabel lblRole4;
    private javax.swing.JLabel lblUserName;
    private javax.swing.JLabel lblUserName4;
    private javax.swing.JPasswordField pfPassword4;
    private javax.swing.JTextField txtPname1;
    private javax.swing.JTextField txtUsername;
    private javax.swing.JTextField txtUsername4;
    // End of variables declaration//GEN-END:variables

    public void SetHospitalID() {
        jLabel1.setText(hospitalid);
        jLabel3.setText(hospitalid);
    }
}
