/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui;

import User.CreateUser;
import Package.ConnectionProvider;
import java.sql.Connection;
import java.sql.Statement;
import javax.swing.JOptionPane;
import java.sql.PreparedStatement;
import Hospital.HospitalList.*;
import Hospital.Doctor.Doctor;
import Hospital.Patient.Patient;
import Hospital.HospitalList.Community;
import com.mysql.cj.jdbc.result.ResultSetMetaData;
import java.sql.ResultSet;
import java.util.Vector;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author Yamini Manral
 */
public class SystemAdmin extends javax.swing.JFrame {

    /**
     * Creates new form SystemAdmin
     */
    public SystemAdmin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel7 = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jTextField25 = new javax.swing.JTextField();
        jButton19 = new javax.swing.JButton();
        jLabel48 = new javax.swing.JLabel();
        jTextField31 = new javax.swing.JTextField();
        jLabel49 = new javax.swing.JLabel();
        jButton28 = new javax.swing.JButton();
        jLabel43 = new javax.swing.JLabel();
        jTextField17 = new javax.swing.JTextField();
        jLabel50 = new javax.swing.JLabel();
        jButton30 = new javax.swing.JButton();
        jLabel52 = new javax.swing.JLabel();
        jTextField18 = new javax.swing.JTextField();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTable5 = new javax.swing.JTable();
        jButton20 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        lblPassword2 = new javax.swing.JLabel();
        cbRole4 = new javax.swing.JComboBox<>();
        lblRole2 = new javax.swing.JLabel();
        pfPassword2 = new javax.swing.JPasswordField();
        txtUsername2 = new javax.swing.JTextField();
        lblUserName2 = new javax.swing.JLabel();
        btnReset2 = new javax.swing.JButton();
        btnGoToLogin2 = new javax.swing.JButton();
        btnCreateUser2 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jButton4 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jTextField23 = new javax.swing.JTextField();
        jButton10 = new javax.swing.JButton();
        jLabel44 = new javax.swing.JLabel();
        jTextField30 = new javax.swing.JTextField();
        jLabel45 = new javax.swing.JLabel();
        jButton12 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable4 = new javax.swing.JTable();
        jButton18 = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        jButton3 = new javax.swing.JButton();
        jLabel28 = new javax.swing.JLabel();
        jTextField14 = new javax.swing.JTextField();
        jLabel42 = new javax.swing.JLabel();
        jButton26 = new javax.swing.JButton();
        jLabel46 = new javax.swing.JLabel();
        jTextField15 = new javax.swing.JTextField();
        jLabel47 = new javax.swing.JLabel();
        jComboBox8 = new javax.swing.JComboBox<>();
        jButton29 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel26 = new javax.swing.JLabel();
        lblPassword3 = new javax.swing.JLabel();
        cbRole5 = new javax.swing.JComboBox<>();
        lblRole3 = new javax.swing.JLabel();
        pfPassword3 = new javax.swing.JPasswordField();
        txtUsername3 = new javax.swing.JTextField();
        lblUserName3 = new javax.swing.JLabel();
        btnGoToLogin3 = new javax.swing.JButton();
        btnCreateUser3 = new javax.swing.JButton();
        jLabel30 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel31 = new javax.swing.JLabel();
        jComboBox5 = new javax.swing.JComboBox<>();
        jButton24 = new javax.swing.JButton();
        btnReset4 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jTextField10 = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        jLabel19 = new javax.swing.JLabel();
        jTextField11 = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jButton7 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        jButton17 = new javax.swing.JButton();
        jLabel22 = new javax.swing.JLabel();
        jTextField13 = new javax.swing.JTextField();
        jTextField16 = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        jButton21 = new javax.swing.JButton();
        jLabel39 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jComboBox4 = new javax.swing.JComboBox<>();
        jButton23 = new javax.swing.JButton();
        jComboBox6 = new javax.swing.JComboBox<>();
        jButton25 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jTextField9 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jButton16 = new javax.swing.JButton();
        jLabel29 = new javax.swing.JLabel();
        jComboBox3 = new javax.swing.JComboBox<>();
        jButton22 = new javax.swing.JButton();
        jLabel40 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        lblPassword4 = new javax.swing.JLabel();
        cbRole6 = new javax.swing.JComboBox<>();
        lblRole4 = new javax.swing.JLabel();
        pfPassword4 = new javax.swing.JPasswordField();
        txtUsername4 = new javax.swing.JTextField();
        lblUserName4 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel41 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel35 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jTextField12 = new javax.swing.JTextField();
        jButton8 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton9 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jTabbedPane1.setBackground(new java.awt.Color(255, 225, 234));
        jTabbedPane1.setTabLayoutPolicy(javax.swing.JTabbedPane.SCROLL_TAB_LAYOUT);
        jTabbedPane1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jPanel7.setBackground(new java.awt.Color(225, 222, 227));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel21.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel21.setText("Add new City");
        jPanel7.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, 364, 30));

        jLabel37.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel37.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel37.setText("Name");
        jPanel7.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 130, 69, 20));

        jTextField25.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jPanel7.add(jTextField25, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 130, 206, 30));

        jButton19.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton19.setText("View City");
        jButton19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton19ActionPerformed(evt);
            }
        });
        jPanel7.add(jButton19, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 200, -1, 50));

        jLabel48.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel48.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel48.setText("Delete City");
        jPanel7.add(jLabel48, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 330, 341, -1));

        jTextField31.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextField31.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField31ActionPerformed(evt);
            }
        });
        jPanel7.add(jTextField31, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 380, 130, 40));

        jLabel49.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel49.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel49.setText("City ID");
        jPanel7.add(jLabel49, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 390, 100, -1));

        jButton28.setBackground(new java.awt.Color(255, 102, 102));
        jButton28.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton28.setText("Delete City");
        jButton28.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton28ActionPerformed(evt);
            }
        });
        jPanel7.add(jButton28, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 440, 160, 50));

        jLabel43.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel43.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel43.setText("Update City");
        jPanel7.add(jLabel43, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 300, 429, -1));

        jTextField17.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jPanel7.add(jTextField17, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 390, 206, -1));

        jLabel50.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel50.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel50.setText("Name");
        jPanel7.add(jLabel50, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 390, 69, 30));

        jButton30.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton30.setText("Update");
        jButton30.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton30ActionPerformed(evt);
            }
        });
        jPanel7.add(jButton30, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 430, -1, 43));

        jLabel52.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel52.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel52.setText("City ID");
        jPanel7.add(jLabel52, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 350, 90, 30));

        jTextField18.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jPanel7.add(jTextField18, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 350, 206, -1));

        jTable5.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "City ID", "City Name"
            }
        ));
        jScrollPane5.setViewportView(jTable5);

        jPanel7.add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 70, 370, 120));

        jButton20.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton20.setText("Add new City");
        jButton20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton20ActionPerformed(evt);
            }
        });
        jPanel7.add(jButton20, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 180, -1, 50));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("System Admin");
        jPanel7.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 20, -1, -1));

        jTabbedPane1.addTab("City", jPanel7);

        jPanel6.setBackground(new java.awt.Color(225, 222, 227));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel17.setFont(new java.awt.Font("Segoe UI Historic", 1, 24)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(133, 88, 111));
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setText("Community Admin Management Page");
        jPanel6.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 850, 53));

        lblPassword2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblPassword2.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblPassword2.setText("Password");
        jPanel6.add(lblPassword2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 240, 86, -1));

        cbRole4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cbRole4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Community Admin", " " }));
        jPanel6.add(cbRole4, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 150, 170, 33));

        lblRole2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblRole2.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblRole2.setText("Role");
        jPanel6.add(lblRole2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 160, 86, -1));

        pfPassword2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pfPassword2ActionPerformed(evt);
            }
        });
        jPanel6.add(pfPassword2, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 230, 170, 36));
        jPanel6.add(txtUsername2, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 190, 170, 33));

        lblUserName2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblUserName2.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblUserName2.setText("Username");
        jPanel6.add(lblUserName2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 200, 86, -1));

        btnReset2.setBackground(new java.awt.Color(255, 102, 102));
        btnReset2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnReset2.setText("Delete");
        btnReset2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReset2ActionPerformed(evt);
            }
        });
        jPanel6.add(btnReset2, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 440, 85, 45));

        btnGoToLogin2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnGoToLogin2.setText("Go to Login Page");
        btnGoToLogin2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGoToLogin2ActionPerformed(evt);
            }
        });
        jPanel6.add(btnGoToLogin2, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 380, -1, 45));

        btnCreateUser2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnCreateUser2.setText("Create User");
        btnCreateUser2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateUser2ActionPerformed(evt);
            }
        });
        jPanel6.add(btnCreateUser2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 380, 119, 45));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel9.setText("Community ID");
        jPanel6.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 320, 110, -1));

        jTextField1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jPanel6.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 280, 170, -1));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel11.setText("Name");
        jPanel6.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 280, 69, -1));

        jComboBox2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jComboBox2MouseClicked(evt);
            }
        });
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });
        jPanel6.add(jComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 320, 130, 30));

        jButton4.setText("Refresh");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel6.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 320, -1, 30));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("System Admin");
        jPanel6.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 20, -1, -1));

        jTabbedPane1.addTab("Community Admin ", jPanel6);

        jPanel2.setBackground(new java.awt.Color(225, 222, 227));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel14.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("Add new Community");
        jPanel2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 364, 30));

        jLabel36.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel36.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel36.setText("Name");
        jPanel2.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, 69, 20));

        jLabel38.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel38.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel38.setText("City ID");
        jPanel2.add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 95, 30));

        jTextField23.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jPanel2.add(jTextField23, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 130, 206, 30));

        jButton10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton10.setText("Add new Community");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton10, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 240, -1, 50));

        jLabel44.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel44.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel44.setText("Delete Community");
        jPanel2.add(jLabel44, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 330, 341, -1));

        jTextField30.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextField30.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField30ActionPerformed(evt);
            }
        });
        jPanel2.add(jTextField30, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 380, 206, 40));

        jLabel45.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel45.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel45.setText("Community ID");
        jPanel2.add(jLabel45, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 390, 100, -1));

        jButton12.setBackground(new java.awt.Color(255, 102, 102));
        jButton12.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton12.setText("Delete Community");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton12, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 440, 160, 50));

        jButton13.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton13.setText("Reset");
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton13, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 240, 78, 50));

        jTable4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTable4.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Community ID", "Name", "City"
            }
        ));
        jScrollPane4.setViewportView(jTable4);

        jPanel2.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 320, 400, 140));

        jButton18.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton18.setText("View Details");
        jButton18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton18ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton18, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 470, -1, 44));

        jComboBox1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jComboBox1MouseClicked(evt);
            }
        });
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        jPanel2.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 170, 130, 30));

        jButton3.setText("Refresh");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 170, -1, 30));

        jLabel28.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel28.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel28.setText("Update Community Details");
        jPanel2.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 60, 429, -1));

        jTextField14.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jPanel2.add(jTextField14, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 150, 206, -1));

        jLabel42.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel42.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel42.setText("Name");
        jPanel2.add(jLabel42, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 150, 69, 30));

        jButton26.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton26.setText("Update");
        jButton26.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton26ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton26, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 240, -1, 43));

        jLabel46.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel46.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel46.setText("Community ID");
        jPanel2.add(jLabel46, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 110, 100, 30));

        jTextField15.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jPanel2.add(jTextField15, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 110, 206, -1));

        jLabel47.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel47.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel47.setText("City ID");
        jPanel2.add(jLabel47, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 190, 95, 30));

        jComboBox8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jComboBox8MouseClicked(evt);
            }
        });
        jComboBox8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox8ActionPerformed(evt);
            }
        });
        jPanel2.add(jComboBox8, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 190, 130, 30));

        jButton29.setText("Refresh");
        jButton29.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton29ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton29, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 190, -1, 30));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setText("System Admin");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 20, -1, -1));

        jTabbedPane1.addTab("Community", jPanel2);

        jPanel5.setBackground(new java.awt.Color(225, 222, 227));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel26.setFont(new java.awt.Font("Segoe UI Historic", 1, 24)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(133, 88, 111));
        jLabel26.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel26.setText("Hospital Admin Creation");
        jPanel5.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 850, 53));

        lblPassword3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblPassword3.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblPassword3.setText("Password");
        jPanel5.add(lblPassword3, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 230, 86, -1));

        cbRole5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cbRole5.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Hospital Admin", " " }));
        jPanel5.add(cbRole5, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 140, 170, 33));

        lblRole3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblRole3.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblRole3.setText("Role");
        jPanel5.add(lblRole3, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 150, 86, -1));

        pfPassword3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pfPassword3ActionPerformed(evt);
            }
        });
        jPanel5.add(pfPassword3, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 220, 170, 36));
        jPanel5.add(txtUsername3, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 180, 170, 33));

        lblUserName3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblUserName3.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblUserName3.setText("Username");
        jPanel5.add(lblUserName3, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 190, 86, -1));

        btnGoToLogin3.setBackground(new java.awt.Color(0, 0, 0));
        btnGoToLogin3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnGoToLogin3.setForeground(new java.awt.Color(255, 255, 255));
        btnGoToLogin3.setText("Go to Login Page");
        btnGoToLogin3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGoToLogin3ActionPerformed(evt);
            }
        });
        jPanel5.add(btnGoToLogin3, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 360, -1, 45));

        btnCreateUser3.setBackground(new java.awt.Color(0, 0, 0));
        btnCreateUser3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnCreateUser3.setForeground(new java.awt.Color(255, 255, 255));
        btnCreateUser3.setText("Create Hospital Admin");
        btnCreateUser3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateUser3ActionPerformed(evt);
            }
        });
        jPanel5.add(btnCreateUser3, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 360, 190, 45));

        jLabel30.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel30.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel30.setText("Hospital ID");
        jPanel5.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 310, 110, 30));

        jTextField2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jPanel5.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 270, 170, 30));

        jLabel31.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel31.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel31.setText("Name");
        jPanel5.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 270, 69, 30));

        jComboBox5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jComboBox5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jComboBox5MouseClicked(evt);
            }
        });
        jComboBox5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox5ActionPerformed(evt);
            }
        });
        jPanel5.add(jComboBox5, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 310, 130, 30));

        jButton24.setBackground(new java.awt.Color(190, 181, 196));
        jButton24.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton24.setText("Refresh");
        jButton24.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton24ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton24, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 310, -1, 30));

        btnReset4.setBackground(new java.awt.Color(255, 102, 102));
        btnReset4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnReset4.setText("Delete");
        btnReset4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReset4ActionPerformed(evt);
            }
        });
        jPanel5.add(btnReset4, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 420, 85, 45));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("System Admin");
        jPanel5.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 20, -1, -1));

        jTabbedPane1.addTab("Hospital Admin", jPanel5);

        jPanel4.setBackground(new java.awt.Color(225, 222, 227));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel16.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText("Add new Hospital");
        jPanel4.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 30, 429, -1));

        jTextField10.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jPanel4.add(jTextField10, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 90, 206, -1));

        jLabel18.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel18.setText("Name");
        jPanel4.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, 69, -1));

        jButton6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton6.setText("Add new Hospital");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 180, -1, 43));

        jLabel19.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel19.setText("Update Hospital Details");
        jPanel4.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, 429, -1));

        jTextField11.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jPanel4.add(jTextField11, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 360, 206, -1));

        jLabel20.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel20.setText("Name");
        jPanel4.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 360, 69, 30));

        jLabel27.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel27.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel27.setText("Community");
        jPanel4.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 400, 95, 30));

        jButton7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton7.setText("Update");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 450, -1, 43));

        jTable3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Hospital ID", "Name", "Community"
            }
        ));
        jScrollPane3.setViewportView(jTable3);

        jPanel4.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 60, 400, 140));

        jButton17.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton17.setText("View Details");
        jButton17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton17ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton17, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 210, -1, 44));

        jLabel22.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel22.setText("Hospital ID");
        jPanel4.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(49, 320, 90, 30));

        jTextField13.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jPanel4.add(jTextField13, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 320, 206, -1));

        jTextField16.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextField16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField16ActionPerformed(evt);
            }
        });
        jPanel4.add(jTextField16, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 390, 206, -1));

        jLabel23.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel23.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel23.setText("Hospital ID");
        jPanel4.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 390, 90, -1));

        jButton21.setBackground(new java.awt.Color(255, 102, 102));
        jButton21.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton21.setText("Delete Hospital");
        jButton21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton21ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton21, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 440, 147, 55));

        jLabel39.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel39.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel39.setText("Delete Hospital");
        jPanel4.add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 330, 378, -1));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel10.setText("Community ID");
        jPanel4.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 110, 30));

        jComboBox4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jComboBox4MouseClicked(evt);
            }
        });
        jComboBox4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox4ActionPerformed(evt);
            }
        });
        jPanel4.add(jComboBox4, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 130, 130, 30));

        jButton23.setText("Refresh");
        jButton23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton23ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton23, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 130, -1, 30));

        jComboBox6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jComboBox6MouseClicked(evt);
            }
        });
        jComboBox6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox6ActionPerformed(evt);
            }
        });
        jPanel4.add(jComboBox6, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 400, 130, 30));

        jButton25.setText("Refresh");
        jButton25.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton25ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton25, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 400, -1, 30));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setText("System Admin");
        jPanel4.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 20, -1, -1));

        jTabbedPane1.addTab("Hospital", jPanel4);

        jPanel1.setBackground(new java.awt.Color(225, 222, 227));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton1.setText("Create new Doctor");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 360, 172, 55));

        jTextField9.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextField9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField9ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField9, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 350, 206, 40));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel12.setText("Doctor ID");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 350, 69, 40));

        jButton5.setBackground(new java.awt.Color(255, 102, 102));
        jButton5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton5.setText("Delete Doctor");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 410, 147, 55));

        jTable2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Doctor ID", "Name", "Hospital"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 60, 400, 140));

        jButton16.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton16.setText("View Details");
        jButton16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton16ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton16, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 220, -1, 44));

        jLabel29.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel29.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel29.setText("Hospital ID");
        jPanel1.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 310, 110, 30));

        jComboBox3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jComboBox3MouseClicked(evt);
            }
        });
        jComboBox3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox3ActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBox3, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 310, 130, 30));

        jButton22.setText("Refresh");
        jButton22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton22ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton22, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 310, -1, 30));

        jLabel40.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel40.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel40.setText("Delete Doctor");
        jPanel1.add(jLabel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 290, 378, -1));

        jLabel33.setFont(new java.awt.Font("Segoe UI Historic", 1, 24)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(133, 88, 111));
        jLabel33.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel33.setText("Doctor Creation");
        jPanel1.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 50, 430, 53));

        lblPassword4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblPassword4.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblPassword4.setText("Password");
        jPanel1.add(lblPassword4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 230, 86, -1));

        cbRole6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cbRole6.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Doctor" }));
        jPanel1.add(cbRole6, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 140, 170, 33));

        lblRole4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblRole4.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblRole4.setText("Role");
        jPanel1.add(lblRole4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 150, 86, -1));

        pfPassword4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pfPassword4ActionPerformed(evt);
            }
        });
        jPanel1.add(pfPassword4, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 220, 170, 36));
        jPanel1.add(txtUsername4, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 180, 170, 33));

        lblUserName4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblUserName4.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblUserName4.setText("Username");
        jPanel1.add(lblUserName4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 190, 86, -1));

        jTextField3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jPanel1.add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 270, 170, -1));

        jLabel41.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel41.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel41.setText("Name");
        jPanel1.add(jLabel41, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 270, 69, 30));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setText("System Admin");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 20, -1, -1));

        jTabbedPane1.addTab("Doctor", jPanel1);

        jPanel3.setBackground(new java.awt.Color(225, 222, 227));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel35.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel35.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel35.setText("Delete Patient");
        jPanel3.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 300, 378, -1));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel13.setText("Person ID");
        jPanel3.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 360, 90, 30));

        jTextField12.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextField12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField12ActionPerformed(evt);
            }
        });
        jPanel3.add(jTextField12, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 360, 206, -1));

        jButton8.setBackground(new java.awt.Color(255, 102, 102));
        jButton8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton8.setText("Delete Patient");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 410, 147, 55));

        jButton11.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton11.setText("View Details");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton11, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 220, -1, 44));

        jTable1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Patient ID", "Name"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jPanel3.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 60, 400, 140));

        jButton9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton9.setText("Logout");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 50, 103, 30));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("System Admin");
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 20, -1, -1));

        jTabbedPane1.addTab("Patients", jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 850, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 594, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:

        //DELETE DOCTOR from  doctor table
        String did = jTextField9.getText();

        Doctor.DeleteDoctor(did);
        jTextField9.setText("");

    }//GEN-LAST:event_jButton5ActionPerformed

    private void jTextField9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField9ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:

        //add new doctor to the doctor table
        String name = jTextField3.getText();
        String role = cbRole6.getSelectedItem().toString();
        String username = txtUsername4.getText();
        String password = pfPassword4.getText();
        String cid = null;
        String hospitalid = jComboBox3.getSelectedItem().toString().substring(0,2);

        CreateUser.NewUser(role, username, password, name, cid, hospitalid);

        jTextField3.setText("");
        txtUsername4.setText("");
        pfPassword4.setText("");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
        // TODO add your handling code here:

        //RESET BUTTON FOR COMMUNITY PAGE
        jTextField23.setText("");
    }//GEN-LAST:event_jButton13ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        // TODO add your handling code here:

        //BUTTON FOR DELETEING COMMUNITY
        String id = jTextField30.getText();

        Community.DeleteCommunity(id);
        jTextField30.setText("");

    }//GEN-LAST:event_jButton12ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        // TODO add your handling code here:

        //COMMUNITY ADD BUTTON
        String name = jTextField23.getText();
        String cityid = jComboBox1.getSelectedItem().toString().substring(0,2);

        Community.CreateCommunity(name, cityid);

        //set to empty fields once data is pushed
        jTextField23.setText("");

    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:

        //ADD NEW HOSPITAL INFO
        String hname = jTextField10.getText();
        String communityid = jComboBox4.getSelectedItem().toString().substring(0,2);

//        new Hospital();
        Hospital.CreateHospital(hname, communityid);

        jTextField10.setText("");
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
        //SYSTEM ADMIN LOGOUT BUTTON FUNCTIONALITY

        int a = JOptionPane.showConfirmDialog(null, "Do you really wanna logout?", "Select", JOptionPane.YES_NO_OPTION);
        if (a == 0) {
            dispose();
            new Login().setVisible(true);
        }
    }//GEN-LAST:event_jButton9ActionPerformed

    private void pfPassword2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pfPassword2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pfPassword2ActionPerformed

    private void btnReset2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReset2ActionPerformed
        // TODO add your handling code here:
        //user creation reset button

        CreateUser.DeleteUser(txtUsername2.getText());

        txtUsername2.setText("");
    }//GEN-LAST:event_btnReset2ActionPerformed

    private void btnGoToLogin2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGoToLogin2ActionPerformed
        // TODO add your handling code here:
        //from user creation page to login page

        int a = JOptionPane.showConfirmDialog(null, "Do you really wanna go to login page?", "Select", JOptionPane.YES_NO_CANCEL_OPTION);
        if (a == 0) {
            setVisible(false);
            new Login().setVisible(true);
        }
    }//GEN-LAST:event_btnGoToLogin2ActionPerformed

    private void btnCreateUser2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateUser2ActionPerformed
//ADD DATA IN persondirectory TABLE BY USER CREATION

        String role = cbRole4.getSelectedItem().toString();
        String username = txtUsername2.getText();
        String password = pfPassword2.getText();
        String name = jTextField1.getText();
        String cid = jComboBox2.getSelectedItem().toString().substring(0,2);

        CreateUser.AddNewCommunityAdmin(role, username, password, name, cid);
        txtUsername2.setText("");
        pfPassword2.setText("");
        jTextField1.setText("");

    }//GEN-LAST:event_btnCreateUser2ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        //UPDATE HOSPITAL INFO TABLE, CLICK TO UPDATE HOSPITAL DETAILS

        String name = jTextField11.getText();
        String communityid = jComboBox6.getSelectedItem().toString().substring(0,2);
        String id = jTextField13.getText();

        Hospital.UpdateHospital(id, name, communityid);


    }//GEN-LAST:event_jButton7ActionPerformed

    private void jTextField12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField12ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:

        //delete patient button
        String id = jTextField12.getText();

        Patient.DeletePatient(id);
        jTextField12.setText("");
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        // TODO add your handling code here:

        //BUTTON TO VIEW PATIENT DETAILS/press only once
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();

        Patient.ReadAllPatient(model);


    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton16ActionPerformed
        // TODO add your handling code here:

        //BUTTON TO VIEW DOCTOR DETAILS FROM THE DATABASE
//        String cname = null;
        DefaultTableModel model = (DefaultTableModel) jTable2.getModel();

        Doctor.ReadAllDoctor(model);
    }//GEN-LAST:event_jButton16ActionPerformed

    private void jButton17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton17ActionPerformed
        // TODO add your handling code here:

        //VIEW BUTTON FOR HOSPITAL LIST
        DefaultTableModel model = (DefaultTableModel) jTable3.getModel();

        Hospital.ReadAllHospital(model);
    }//GEN-LAST:event_jButton17ActionPerformed

    private void jButton18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton18ActionPerformed
        // TODO add your handling code here:

        //VIEW BUTTON FOR COMMUNITY TABLE
        DefaultTableModel model = (DefaultTableModel) jTable4.getModel();

        Community.ReadAllCommunity(model);
    }//GEN-LAST:event_jButton18ActionPerformed

    private void jButton19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton19ActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) jTable5.getModel();

        City.ReadAllCity(model);
    }//GEN-LAST:event_jButton19ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jComboBox1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboBox1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1MouseClicked

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:

        try {
            Connection connection = ConnectionProvider.Connect();
            Statement statement = connection.createStatement();

            String query = "Select * from hospital.citydirectory";
            ResultSet rs = statement.executeQuery(query);
            jComboBox1.removeAllItems();
            while (rs.next()) {
//                String name = rs.getString("cityname");
                String id = rs.getString("cityid");
                String name = rs.getString("cityname");
//                String item = String.join(" ", id);
                jComboBox1.addItem(String.join(" ", id, name));
            }
            connection.close();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jTextField16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField16ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField16ActionPerformed

    private void jButton21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton21ActionPerformed
        // TODO add your handling code here:

        //BUTTON FOR DELETING HOSPITAL
        String id = jTextField16.getText();

        Hospital.DeleteHospital(id);
        jTextField16.setText("");
    }//GEN-LAST:event_jButton21ActionPerformed

    private void jComboBox2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboBox2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox2MouseClicked

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:

        //refresh list of community
        try {
            Connection connection = ConnectionProvider.Connect();
            Statement statement = connection.createStatement();

            String query = "Select * from hospital.communitydirectory";
            ResultSet rs = statement.executeQuery(query);
            jComboBox2.removeAllItems();
            while (rs.next()) {
                String id = rs.getString("communityid");
                String name = rs.getString("name");
                jComboBox2.addItem(String.join(" ", id, name));
            }
            connection.close();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jComboBox3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboBox3MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox3MouseClicked

    private void jComboBox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox3ActionPerformed

    private void jButton22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton22ActionPerformed
        // TODO add your handling code here:

        //refresh hospital drop down
        try {
            Connection connection = ConnectionProvider.Connect();
            Statement statement = connection.createStatement();

            String query = "Select * from hospital.hospitaldirectory";
            ResultSet rs = statement.executeQuery(query);
            jComboBox3.removeAllItems();
            while (rs.next()) {
                String id = rs.getString("hospitalid");
                String name = rs.getString("name");
                jComboBox3.addItem(String.join(" ", id, name));
            }
            connection.close();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_jButton22ActionPerformed

    private void jComboBox4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboBox4MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox4MouseClicked

    private void jComboBox4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox4ActionPerformed

    private void jButton23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton23ActionPerformed
        // TODO add your handling code here:

        //refresh for community on hospital page
        try {
            Connection connection = ConnectionProvider.Connect();
            Statement statement = connection.createStatement();

            String query = "Select * from hospital.communitydirectory";
            ResultSet rs = statement.executeQuery(query);
            jComboBox4.removeAllItems();
            while (rs.next()) {
                String id = rs.getString("communityid");
                String name = rs.getString("name");
                jComboBox4.addItem(String.join(" ", id, name));
            }
            connection.close();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }

    }//GEN-LAST:event_jButton23ActionPerformed

    private void jTextField30ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField30ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField30ActionPerformed

    private void pfPassword3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pfPassword3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pfPassword3ActionPerformed

    private void btnGoToLogin3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGoToLogin3ActionPerformed
        // TODO add your handling code here:

        int a = JOptionPane.showConfirmDialog(null, "Do you really wanna go to login page?", "Select", JOptionPane.YES_NO_OPTION);
        if (a == 0) {
            setVisible(false);
            new Login().setVisible(true);
        }
    }//GEN-LAST:event_btnGoToLogin3ActionPerformed

    private void btnCreateUser3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateUser3ActionPerformed
        // TODO add your handling code here:

        //
        String role = cbRole5.getSelectedItem().toString();
        String username = txtUsername3.getText();
        String password = pfPassword3.getText();
        String name = jTextField2.getText();
        String hid = jComboBox5.getSelectedItem().toString().substring(0,2);
        String cid = null;

        CreateUser.NewUser(role, username, password, name, cid, hid);
        txtUsername3.setText("");
        pfPassword3.setText("");
        jTextField2.setText("");
    }//GEN-LAST:event_btnCreateUser3ActionPerformed

    private void jComboBox5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboBox5MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox5MouseClicked

    private void jComboBox5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox5ActionPerformed

    private void jButton24ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton24ActionPerformed
        // TODO add your handling code here:

        //refresh button for hospital ids
        try {
            Connection connection = ConnectionProvider.Connect();
            Statement statement = connection.createStatement();

            String query = "Select * from hospital.hospitaldirectory";
            ResultSet rs = statement.executeQuery(query);
            jComboBox5.removeAllItems();
            while (rs.next()) {
                String id = rs.getString("hospitalid");
                String name = rs.getString("name");
                jComboBox5.addItem(String.join(" ", id, name));
            }
            connection.close();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }

    }//GEN-LAST:event_jButton24ActionPerformed

    private void jComboBox6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboBox6MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox6MouseClicked

    private void jComboBox6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox6ActionPerformed

    private void jButton25ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton25ActionPerformed
        // TODO add your handling code here:

        //REFRESH COMMUNITY
        try {
            Connection connection = ConnectionProvider.Connect();
            Statement statement = connection.createStatement();

            String query = "Select * from hospital.communitydirectory";
            ResultSet rs = statement.executeQuery(query);
            jComboBox6.removeAllItems();
            while (rs.next()) {
                String id = rs.getString("communityid");
                String name = rs.getString("name");
                jComboBox6.addItem(String.join(" ", id, name));
            }
            connection.close();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_jButton25ActionPerformed

    private void pfPassword4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pfPassword4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pfPassword4ActionPerformed

    private void jButton26ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton26ActionPerformed
        // TODO add your handling code here:
        
        Community.UpdateCommunity(jTextField15.getText(), jTextField14.getText(), jComboBox8.getSelectedItem().toString().substring(0,2));
        jTextField15.setText("");
        jTextField14.setText("");
        
    }//GEN-LAST:event_jButton26ActionPerformed

    private void jComboBox8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboBox8MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox8MouseClicked

    private void jComboBox8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox8ActionPerformed

    private void jButton29ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton29ActionPerformed
        // TODO add your handling code here:
        
         try {
            Connection connection = ConnectionProvider.Connect();
            Statement statement = connection.createStatement();

            String query = "Select * from hospital.citydirectory";
            ResultSet rs = statement.executeQuery(query);
            jComboBox8.removeAllItems();
            while (rs.next()) {
                String name = rs.getString("cityname");
                String id = rs.getString("cityid");
                jComboBox8.addItem(String.join(" ", id, name));
            }
            connection.close();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_jButton29ActionPerformed

    private void jTextField31ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField31ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField31ActionPerformed

    private void jButton28ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton28ActionPerformed
        // TODO add your handling code here:

        //delete city
        City.DeleteCity(jTextField31.getText());
        jTextField31.setText("");
    }//GEN-LAST:event_jButton28ActionPerformed

    private void jButton30ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton30ActionPerformed
        // TODO add your handling code here:

        //update city
        City.UpdateCity(jTextField18.getText(), jTextField17.getText());
        jTextField18.setText("");
    }//GEN-LAST:event_jButton30ActionPerformed

    private void jButton20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton20ActionPerformed
        // TODO add your handling code here:
        
        //create city;
        
        City.CreateCity(jTextField25.getText());
        jTextField25.setText("");
    }//GEN-LAST:event_jButton20ActionPerformed

    private void btnReset4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReset4ActionPerformed
        // TODO add your handling code here:
        
        CreateUser.DeleteUser(txtUsername3.getText());

        txtUsername3.setText("");
    }//GEN-LAST:event_btnReset4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("FlatLaf Light".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SystemAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SystemAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SystemAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SystemAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SystemAdmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCreateUser2;
    private javax.swing.JButton btnCreateUser3;
    private javax.swing.JButton btnGoToLogin2;
    private javax.swing.JButton btnGoToLogin3;
    private javax.swing.JButton btnReset2;
    private javax.swing.JButton btnReset4;
    private javax.swing.JComboBox<String> cbRole4;
    private javax.swing.JComboBox<String> cbRole5;
    private javax.swing.JComboBox<String> cbRole6;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton19;
    private javax.swing.JButton jButton20;
    private javax.swing.JButton jButton21;
    private javax.swing.JButton jButton22;
    private javax.swing.JButton jButton23;
    private javax.swing.JButton jButton24;
    private javax.swing.JButton jButton25;
    private javax.swing.JButton jButton26;
    private javax.swing.JButton jButton28;
    private javax.swing.JButton jButton29;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton30;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JComboBox<String> jComboBox4;
    private javax.swing.JComboBox<String> jComboBox5;
    private javax.swing.JComboBox<String> jComboBox6;
    private javax.swing.JComboBox<String> jComboBox8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable3;
    private javax.swing.JTable jTable4;
    private javax.swing.JTable jTable5;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField13;
    private javax.swing.JTextField jTextField14;
    private javax.swing.JTextField jTextField15;
    private javax.swing.JTextField jTextField16;
    private javax.swing.JTextField jTextField17;
    private javax.swing.JTextField jTextField18;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField23;
    private javax.swing.JTextField jTextField25;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField30;
    private javax.swing.JTextField jTextField31;
    private javax.swing.JTextField jTextField9;
    private javax.swing.JLabel lblPassword2;
    private javax.swing.JLabel lblPassword3;
    private javax.swing.JLabel lblPassword4;
    private javax.swing.JLabel lblRole2;
    private javax.swing.JLabel lblRole3;
    private javax.swing.JLabel lblRole4;
    private javax.swing.JLabel lblUserName2;
    private javax.swing.JLabel lblUserName3;
    private javax.swing.JLabel lblUserName4;
    private javax.swing.JPasswordField pfPassword2;
    private javax.swing.JPasswordField pfPassword3;
    private javax.swing.JPasswordField pfPassword4;
    private javax.swing.JTextField txtUsername2;
    private javax.swing.JTextField txtUsername3;
    private javax.swing.JTextField txtUsername4;
    // End of variables declaration//GEN-END:variables
}
